import Head from "next/head";
import Events from "../Components/Events";
import Header from "../components/Header";
import Hero from "../Components/Hero";
import Footer from "../Components/Footer";

export default function Home() {
  return (
    <div className="h-screen">
      <Head>
        <title>Nkwazi Events Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid-container">
        <Header />
        <Hero />
        <Events />
        <Footer />
      </main>
    </div>
  );
}

